### PR TITLE
Redmine issue 1931: Footprint correction for specular simulation

### PR DESCRIPTION
**Pull request by DmitryYurov**
Not functional for now

### CODE REVIEW

**Comment by gpospelov** [comment]
Why not to localize all in single class - FootprintCorrection. There can be characteristic sample size, beam shape and necessary calculations. In my opinion there is no strong need to couple it with MultiLayer.

**Comment by DmitryYurov** [comment]
I don't have objections except that FootprintCorrection is an abstract entity. Assigning beam shape (a better name than BeamFormFactor, by the way) to the beam and a dimension to the sample is more natural from user point of view.

**Comment by DmitryYurov** [comment]
You are right of course, that adding one more parameter to MultiLayer does no good. FootprintCorrection class would enable us to avoid extension of MultiLayer class.

**Comment by gpospelov** [comment]
I don't mind to proceed like it is now. We can change it later, if necessary. I don't know what will be more natural from user point of view. But from GUI perspective, having all numbers responsible for footprint in one place (InstrumentWidget), make it easier to tune.

**Comment by DmitryYurov** [comment]
Ok, I will have it in mind in course of future work.

**Pull request merged**
