### PR TITLE
Fix O(n_layer^2) bug

### PR DESCRIPTION
**Pull request by DmitryYurov**
Before:

n_layers = 10,	 time = 4 ms
n_layers = 100,	 time = 64 ms
n_layers = 200,	 time = 349 ms
n_layers = 500,	 time = 4547 ms
n_layers = 1000,	 time = 34026 ms

After:

n_layers = 10,	 time = 4 ms
n_layers = 100,	 time = 28 ms
n_layers = 200,	 time = 52 ms
n_layers = 500,	 time = 210 ms
n_layers = 1000,	 time = 646 ms

### CODE REVIEW

**Comment by gpospelov** [comment]
Very cool! Such nasty and long playing bug is finally resolved. Thank you!

**Comment by DmitryYurov** [comment]
Thank you, sir! It's just our job to make the world a better place.

**Comment by juanmcloaiza** [comment]
Great Dmitry!! 👌🏾🎉

**Comment by juanmcloaiza** [comment]
Good news: Timings are indeed much better than before.

Bad news: Timings are still scaling as $O(N^2)$, though it is only noticeable for large numbers of layers.

From the numbers @DmitryYurov provided, the trend is not clearly noticeable,

image

but carrying on the analysis with more and more layers, the trend is clearer:

image

**Comment by DmitryYurov** [comment]
Yes, indeed something is still slowing down the computation on samples with an extremely big number of layers. Looking into it right now.

**Pull request merged**
