### PR TITLE
Change Ripple1 API and implementation

### PR DESCRIPTION
**Pull request by jwuttke**
* Make names more uniform: FormFactorRipple1* where *=Box,Gauss,Lorentz
* Implementation through inheritance from ProfileRipple1
* Form factor in elongation direction x computed in namespace ripples
* rm unused FormFactorLongBox
* Update FFCatalog
* Add developer note on files that are affected by ff API changes
   
This addresses the Ripple1 part of http://apps.jcns.fz-juelich.de/redmine/issues/2455

### CODE REVIEW

**Comment by gpospelov** [comment]
+ Absent icon for ParticleItem when selecting Ripple1Box on SampleDesigner canvas.
+ GUI crashes when trying to select Ripple1Gauss.
+ The last commit contains 40 changed files and should be, ideally, split into several commits to group closely related changes together.

**Comment by jwuttke** [comment]
@gpospelov Thanks for the review. Indeed I should have tried the GUI instead of relying on CTest only.

**Comment by jwuttke** [comment]
Almost all of the changes in the last commit, which concerned 40 files, were necessary to propagate some changes in form factor names through Core and GUI. This needs to be simplified: http://apps.jcns.fz-juelich.de/redmine/issues/2457

**Comment by jwuttke** [comment]
Closing this issue while working on the outstanding GUI issues.

**Pull request merged**
