### PR TITLE
[preview, don't merge] Core reformatted with clang-format-3.9

### PR DESCRIPTION
**Pull request by jwuttke**
This is not yet meant to be a pull request, but a preview to be discussed on Monday.

Style settings for clang-format-3.9:

Language: Cpp
Standard: Cpp11
BasedOnStyle: WebKit
IndentWidth: 4
UseTab: Never

AccessModifierOffset: -4
AlignAfterOpenBracket: AlwaysBreak
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignOperands: false
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterReturnType: None
BinPackArguments: true
BinPackParameters: true
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Linux
ColumnLimit: 100
CommentPragmas: \/\/!
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: false
DerivePointerAlignment: false
IndentCaseLabels: false
IndentWrappedFunctionNames: false
MaxEmptyLinesToKeep: 2
PointerAlignment: Left
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: false

### CODE REVIEW

**Comment by gpospelov** [comment]
Please consider creation of your own Travis account and testing your branch on side to not to generate unnecessary pull requests. Jan or me could help you with that.

**Comment by waltervh** [comment]
Please refer to your personal fork for showing us implications for the code that are not to be merged.

**Comment by jwuttke** [comment]
Compilation failed because clang-format also does an alphabetic sort of #include "..." lines. This is easy to fix by moving a few #include <...> lines to .h files.

**Comment by waltervh** [comment]
Is there a possibility to just let clang not touch include lines? I find it kind of reverse logic to change our include structure so clang can deal with it.

**Comment by jwuttke** [comment]
Our include files _are_ alphabetically sorted (within the groups <this file> <our other h files> <system files>) since about commit cffe5; this auto-formatting would mostly fix a few inconsistencies slipped in e.g. by renaming files.

**Comment by waltervh** [comment]
Another thing to consider: running all kinds of automatic tools on our code base messes up useful tools like git blame, since they will report the last person running the automatic tool, instead of the person responsible for the line of code.

**Comment by gpospelov** [comment]
I have my doubt that clang automatic tool will be useful on the whole code base. It will generate massive code changes (and so terrible pull requests) and it will not be smart enough to respect all our custom formatting (as it did now in Core/HardParticle/FormFactorIcosahedron.cpp). But clang can be useful for Qt-creator users if we find configuration with spaces in correct places, so we shouldn't worry while auto generated code snippets. I would postpone clang experiments in upstream and focus on hotfix release.

**Comment by waltervh** [comment]
My suggestion would be to:
-change on the fly those pieces of code one is working on
-define a style file in our IDEs so the new code is automatically in the same style

**Comment by mganeva** [comment]
I am fully agree with Gennagy and Walter. The best would be to reformat those parts of code is one working on. So we keep the control on the changes and avoid surprizes introduced by automatical code formating tools.

**Pull request closed without merging**
